repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: accounts-api
    labels:
      app: accounts-api
    wait: true
    chart: bitnami/aspnet-core
    version: 4.4.7
    values:
      - values.yaml
      - image:
          tag: "{{ .StateValues.image.tag }}"
      - ingress:
          hostname: "{{ .StateValues.ingress.hostname }}"
      - extraSecretEnvVars:
          ConnectionStrings__DefaultConnection: "{{ .StateValues.extraSecretEnvVars.ConnectionStrings__DefaultConnection }}"
          AuthenticationOptions__PublicSigningKey: "{{ .StateValues.extraSecretEnvVars.AuthenticationOptions__PublicSigningKey }}"
          HttpUrls__AuthServiceUrl: "{{ .StateValues.extraSecretEnvVars.HttpUrls__AuthServiceUrl }}"
          HttpUrls__EmployeesServiceUrl: "{{ .StateValues.extraSecretEnvVars.HttpUrls__EmployeesServiceUrl }}"
          AccountValidationOptions__CorporateEmailDomain: "{{ .StateValues.extraSecretEnvVars.AccountValidationOptions__CorporateEmailDomain }}"
          AccountValidationOptions__IgnoreCorporateDomainValidationRule: "{{ .StateValues.extraSecretEnvVars.AccountValidationOptions__IgnoreCorporateDomainValidationRule }}"