name: Deploy to Prod

on:
  push:
    branches:
      - master
      - feature/fix_auth_client

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/.reusable-docker-build-and-push.yml

  deploy-to-prod:
    needs: [docker-build-and-push]
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy
        # We use quotes because without them some vars can break down other vars
        run: |
            helmfile cache cleanup && helmfile apply --suppress-diff --namespace "${{ secrets.INNER_CIRCLE_PROD_NAMESPACE }}" -f Api/ci/helmfile.yaml \
            --state-values-set image.tag="sha-${{ github.sha }}" \
            --state-values-set ingress.hostname="${{ secrets.INNER_CIRCLE_PROD_HOSTNAME }}" \
            --state-values-set extraSecretEnvVars.ConnectionStrings__DefaultConnection="${{ secrets.INNER_CIRCLE_PROD_ACCOUNTS_DB_CONNECTION_STRING }}" \
            --state-values-set extraSecretEnvVars.AuthenticationOptions__PublicSigningKey="${{ secrets.INNER_CIRCLE_PROD_PUBLIC_SIGNING_KEY }}" \
            --state-values-set extraSecretEnvVars.HttpUrls__AuthServiceUrl="${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}" \
            --state-values-set extraSecretEnvVars.HttpUrls__EmployeesServiceUrl="${{ secrets.INNER_CIRCLE_PROD_EMPLOYEES_API_ROOT_URL }}" \
            --state-values-set extraSecretEnvVars.AccountValidationOptions__CorporateEmailDomain="${{ secrets.INNER_CIRCLE_PROD_CORPORATE_EMAIL_DOMAIN }}" \
            --state-values-set extraSecretEnvVars.AccountValidationOptions__IgnoreCorporateDomainValidationRule="${{ secrets.INNER_CIRCLE_PROD_IGNORE_CORPORATE_DOMAIN_VALIDATION_RULE }}" > /dev/null 2>&1

  run-e2e-tests:
    uses: ./.github/workflows/.reusable-e2e-tests-against-prod.yml
    needs: [deploy-to-prod]
    secrets: inherit
